version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bettercope
    restart: unless-stopped
    ports:
      - "3000:8080"
    deploy:
      resources:
        limits:
          memory: 150M
